build:
  test-and-lint:
    image: node:6
    environment:
      - NPM_CONFIG_CACHE=/drone/.npm
      - NPM_CONFIG_LOGLEVEL=warn
    commands:
      - npm i -g yarn
      - yarn
      - npm run lint
      - npm test

cache:
  mount:
    - /drone/.npm
