// flow-typed signature: 19c574a9c2eadb446cb926b8b76d99b7
// flow-typed version: <<STUB>>/eslint-config-buildo_vgithub:buildo/eslint-config/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-buildo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-buildo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-buildo/rules/default' {
  declare module.exports: any;
}

declare module 'eslint-config-buildo/test/code/MyComponent' {
  declare module.exports: any;
}

declare module 'eslint-config-buildo/test/validate-config.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-buildo/index' {
  declare module.exports: $Exports<'eslint-config-buildo'>;
}
declare module 'eslint-config-buildo/index.js' {
  declare module.exports: $Exports<'eslint-config-buildo'>;
}
declare module 'eslint-config-buildo/rules/default.js' {
  declare module.exports: $Exports<'eslint-config-buildo/rules/default'>;
}
declare module 'eslint-config-buildo/test/code/MyComponent.js' {
  declare module.exports: $Exports<'eslint-config-buildo/test/code/MyComponent'>;
}
declare module 'eslint-config-buildo/test/validate-config.test.js' {
  declare module.exports: $Exports<'eslint-config-buildo/test/validate-config.test'>;
}
