// flow-typed signature: 40ae2a0c11a34a732e68484caa611aa4
// flow-typed version: <<STUB>>/smooth-release_v^6.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'smooth-release'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'smooth-release' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'smooth-release/lib/config' {
  declare module.exports: any;
}

declare module 'smooth-release/lib/github/changelog' {
  declare module.exports: any;
}

declare module 'smooth-release/lib/github/release' {
  declare module.exports: any;
}

declare module 'smooth-release/lib/github/token' {
  declare module.exports: any;
}

declare module 'smooth-release/lib/index' {
  declare module.exports: any;
}

declare module 'smooth-release/lib/modules/getAllClosedIssues' {
  declare module.exports: any;
}

declare module 'smooth-release/lib/modules/getAllTags' {
  declare module.exports: any;
}

declare module 'smooth-release/lib/npm/publish' {
  declare module.exports: any;
}

declare module 'smooth-release/lib/npm/version' {
  declare module.exports: any;
}

declare module 'smooth-release/lib/utils' {
  declare module.exports: any;
}

declare module 'smooth-release/lib/validations/index' {
  declare module.exports: any;
}

declare module 'smooth-release/src/config' {
  declare module.exports: any;
}

declare module 'smooth-release/src/github/changelog' {
  declare module.exports: any;
}

declare module 'smooth-release/src/github/release' {
  declare module.exports: any;
}

declare module 'smooth-release/src/github/token' {
  declare module.exports: any;
}

declare module 'smooth-release/src/index' {
  declare module.exports: any;
}

declare module 'smooth-release/src/modules/getAllClosedIssues' {
  declare module.exports: any;
}

declare module 'smooth-release/src/modules/getAllTags' {
  declare module.exports: any;
}

declare module 'smooth-release/src/npm/publish' {
  declare module.exports: any;
}

declare module 'smooth-release/src/npm/version' {
  declare module.exports: any;
}

declare module 'smooth-release/src/utils' {
  declare module.exports: any;
}

declare module 'smooth-release/src/validations/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'smooth-release/lib/config.js' {
  declare module.exports: $Exports<'smooth-release/lib/config'>;
}
declare module 'smooth-release/lib/github/changelog.js' {
  declare module.exports: $Exports<'smooth-release/lib/github/changelog'>;
}
declare module 'smooth-release/lib/github/release.js' {
  declare module.exports: $Exports<'smooth-release/lib/github/release'>;
}
declare module 'smooth-release/lib/github/token.js' {
  declare module.exports: $Exports<'smooth-release/lib/github/token'>;
}
declare module 'smooth-release/lib/index.js' {
  declare module.exports: $Exports<'smooth-release/lib/index'>;
}
declare module 'smooth-release/lib/modules/getAllClosedIssues.js' {
  declare module.exports: $Exports<'smooth-release/lib/modules/getAllClosedIssues'>;
}
declare module 'smooth-release/lib/modules/getAllTags.js' {
  declare module.exports: $Exports<'smooth-release/lib/modules/getAllTags'>;
}
declare module 'smooth-release/lib/npm/publish.js' {
  declare module.exports: $Exports<'smooth-release/lib/npm/publish'>;
}
declare module 'smooth-release/lib/npm/version.js' {
  declare module.exports: $Exports<'smooth-release/lib/npm/version'>;
}
declare module 'smooth-release/lib/utils.js' {
  declare module.exports: $Exports<'smooth-release/lib/utils'>;
}
declare module 'smooth-release/lib/validations/index.js' {
  declare module.exports: $Exports<'smooth-release/lib/validations/index'>;
}
declare module 'smooth-release/src/config.js' {
  declare module.exports: $Exports<'smooth-release/src/config'>;
}
declare module 'smooth-release/src/github/changelog.js' {
  declare module.exports: $Exports<'smooth-release/src/github/changelog'>;
}
declare module 'smooth-release/src/github/release.js' {
  declare module.exports: $Exports<'smooth-release/src/github/release'>;
}
declare module 'smooth-release/src/github/token.js' {
  declare module.exports: $Exports<'smooth-release/src/github/token'>;
}
declare module 'smooth-release/src/index.js' {
  declare module.exports: $Exports<'smooth-release/src/index'>;
}
declare module 'smooth-release/src/modules/getAllClosedIssues.js' {
  declare module.exports: $Exports<'smooth-release/src/modules/getAllClosedIssues'>;
}
declare module 'smooth-release/src/modules/getAllTags.js' {
  declare module.exports: $Exports<'smooth-release/src/modules/getAllTags'>;
}
declare module 'smooth-release/src/npm/publish.js' {
  declare module.exports: $Exports<'smooth-release/src/npm/publish'>;
}
declare module 'smooth-release/src/npm/version.js' {
  declare module.exports: $Exports<'smooth-release/src/npm/version'>;
}
declare module 'smooth-release/src/utils.js' {
  declare module.exports: $Exports<'smooth-release/src/utils'>;
}
declare module 'smooth-release/src/validations/index.js' {
  declare module.exports: $Exports<'smooth-release/src/validations/index'>;
}
