resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: master
    type: git
    icon: github-circle
    source:
      uri: git@github.com:buildo/local-date
      branch: master
      private_key: ((private-key))

  - name: pr
    type: pull-request
    source:
      repository: buildo/local-date
      access_token: ((github-token))

jobs:
  - name: pr-test
    plan:
      - get: local-date
        resource: pr
        trigger: true
        version: every
      - put: pr
        params:
          path: local-date
          status: pending
          context: concourse
      - do:
          - task: test
            file: local-date/ci/test.yml
            attempts: 2
        on_success:
          put: pr
          params:
            path: local-date
            status: success
            context: concourse
        on_failure:
          put: pr
          params:
            path: local-date
            status: failure
            context: concourse

  - name: test
    plan:
      - get: local-date
        resource: master
        trigger: true
      - do:
          - task: test
            file: local-date/ci/test.yml
            attempts: 2
